### ISSUE TITLE
Problem loading data from course [APLICACIONES DE BASES DE DATOS (Grupo 1) Presencial]

### ISSUE THREAD

**Issue by rmartico** [RobertoArastiBlanco/eLearningQA#46]
Exception loading data from my course: [APLICACIONES DE BASES DE DATOS (Grupo 1) Presencial]

java.lang.NullPointerException: null
	at es.ubu.lsi.WebServiceClient.hayRetroalimentacion(WebServiceClient.java:384) ~[classes/:na]
	at es.ubu.lsi.ELearningQAFacade.isHayRetroalimentacion(ELearningQAFacade.java:174) ~[classes/:na]
	at es.ubu.lsi.ELearningQAFacade.realizarComprobaciones(ELearningQAFacade.java:91) ~[classes/:na]
	at org.apache.jsp.WEB_002dINF.jsp.informe_jsp._jspService(informe_jsp.java:160) ~[na:na]
	at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:71) [tomcat-embed-jasper-9.0.37.jar:9.0.37]

**Comment by RobertoArastiBlanco** [comment]
Last commit might have solved the problem.
If the problem persists, please send the new stack trace.

**Comment by rmartico** [comment]
I got the same problem again. This is the stack trace;

2022-04-18 10:37:38.331 ERROR 15372 --- [io-8080-exec-10] o.a.jsp.WEB_002dINF.jsp.informe_jsp      : exception

java.lang.NullPointerException: null
	at es.ubu.lsi.WebServiceClient.hayRetroalimentacion(WebServiceClient.java:385) ~[classes/:na]
	at es.ubu.lsi.ELearningQAFacade.isHayRetroalimentacion(ELearningQAFacade.java:174) ~[classes/:na]
	at es.ubu.lsi.ELearningQAFacade.realizarComprobaciones(ELearningQAFacade.java:91) ~[classes/:na]
	at org.apache.jsp.WEB_002dINF.jsp.informe_jsp._jspService(informe_jsp.java:162) ~[na:na]
	at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:71) [tomcat-embed-jasper-9.0.37.jar:9.0.37]

**Comment by RobertoArastiBlanco** [comment]
I think previous commit narrowed down the source.

**Comment by rmartico** [comment]
Now, I can see the result page. Solved.
