### ISSUE TITLE
Bug loading list of courses

### ISSUE THREAD

**Issue by rmartico** [RobertoArastiBlanco/eLearningQA#55]
Reading the list of courses:

java.io.FileNotFoundException: registry\ubuvirtual.ubu.es\Marticorena Sanchez, Raul\2184.csv (El sistema no puede encontrar la ruta especificada)
	at java.io.FileOutputStream.open0(Native Method) ~[na:1.8.0_252]
	at java.io.FileOutputStream.open(FileOutputStream.java:270) ~[na:1.8.0_252]
	at java.io.FileOutputStream.<init>(FileOutputStream.java:213) ~[na:1.8.0_252]
	at java.io.FileOutputStream.<init>(FileOutputStream.java:133) ~[na:1.8.0_252]
	at java.io.FileWriter.<init>(FileWriter.java:78) ~[na:1.8.0_252]
	at es.ubu.lsi.RegistryIO.guardarResultados(RegistryIO.java:37) ~[classes/:na]
	at org.apache.jsp.WEB_002dINF.jsp.informe_jsp._jspService(informe_jsp.java:175) [ROOT/:na]

**Comment by RobertoArastiBlanco** [comment]
Did the exception only occur when accessing a specific course.
I failed to replicate the error.

**Comment by rmartico** [comment]
With any course. It's looking for a csv file for the course, with that id (e.g. id=2184 in previous examples). And, it doesn't exist. Althought, the report is generated correctly for that course on the screen.
